
services:
  db:
    image: postgres:15
    container_name: cucm_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: cucm_app
    restart: always
    # מריץ את האפליקציה על פורט 8000 בתוך הקונטיינר
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8080:8000" # אתה תיכנס דרך http://localhost:8080
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: