"""setup_full_schema_v1

Revision ID: 359fc1f487b0
Revises: bfc8843bdb15
Create Date: 2026-03-29 22:05:55.344982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359fc1f487b0'
down_revision: Union[str, None] = 'bfc8843bdb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sections', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('sections', sa.Column('classification', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False))
    op.add_column('sections', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'sections', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    op.add_column('sites', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_section_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'email')
    op.drop_column('users', 'section_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key('users_section_id_fkey', 'users', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'created_at')
    op.drop_column('sites', 'created_at')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'created_at')
    op.drop_column('sections', 'classification')
    op.drop_column('sections', 'description')
    op.drop_table('section_sites')
    # ### end Alembic commands ###
