"""add role to users table

Revision ID: 59a341c6b11c
Revises: 5b5eb318000c
Create Date: 2026-03-20 16:35:02.466769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a341c6b11c'
down_revision: Union[str, None] = '5b5eb318000c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name="userrole").create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False, server_default='VIEWER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
